import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// You'll need to update this with your actual Clerk user ID
// You can find it in Clerk dashboard or browser console when logged in
const USER_ID = process.argv[2] || 'user_placeholder'

const properties = [
  {
    title: 'Luxury Penthouse in Crystal Tower',
    description: 'Stunning penthouse apartment with panoramic city views. This exclusive residence features floor-to-ceiling windows, premium finishes throughout, and a private rooftop terrace. The open-concept living area is perfect for entertaining, while the gourmet kitchen boasts top-of-the-line appliances. Master suite includes a spa-like bathroom and walk-in closet. Building amenities include 24/7 concierge, fitness center, and rooftop pool.',
    propertyType: 'APARTMENT',
    listingType: 'SALE',
    price: 1250000,
    address: '500 Crystal Tower Drive, Unit PH1',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    district: 'Manhattan',
    nearestMetro: 'Penn Station',
    metroDistance: 5,
    latitude: 40.7505,
    longitude: -73.9934,
    area: 2800,
    livingArea: 2200,
    kitchenArea: 350,
    rooms: 6,
    bedrooms: 3,
    bathrooms: 2.5,
    floor: 25,
    totalFloors: 25,
    yearBuilt: 2021,
    ceilingHeight: 12,
    balcony: 2,
    loggia: 0,
    parking: 2,
    parkingType: 'UNDERGROUND',
    buildingType: 'MONOLITHIC',
    buildingClass: 'ELITE',
    buildingName: 'Crystal Tower',
    elevatorPassenger: 3,
    elevatorCargo: 1,
    hasGarbageChute: true,
    hasConcierge: true,
    hasGatedArea: true,
    renovation: 'DESIGNER',
    windowView: 'PANORAMIC',
    bathroomType: 'MULTIPLE',
    furnished: 'FULL',
  },
  {
    title: 'Modern 2BR in Downtown Business District',
    description: 'Beautifully renovated 2-bedroom apartment in the heart of the business district. Euro-style renovation with high-quality materials. Open kitchen with island, spacious living room with city views. Both bedrooms feature built-in wardrobes. Walking distance to major offices, restaurants, and shopping centers. Perfect for young professionals.',
    propertyType: 'APARTMENT',
    listingType: 'RENT',
    price: 3500,
    address: '123 Business Center Ave, Apt 1204',
    city: 'New York',
    state: 'NY',
    zipCode: '10005',
    district: 'Financial District',
    nearestMetro: 'Wall Street',
    metroDistance: 3,
    latitude: 40.7074,
    longitude: -74.0113,
    area: 1100,
    livingArea: 750,
    kitchenArea: 180,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    floor: 12,
    totalFloors: 20,
    yearBuilt: 2015,
    ceilingHeight: 9.5,
    balcony: 1,
    loggia: 0,
    parking: 1,
    parkingType: 'UNDERGROUND',
    buildingType: 'MONOLITHIC',
    buildingClass: 'BUSINESS',
    buildingName: 'Business Center Residences',
    elevatorPassenger: 2,
    elevatorCargo: 1,
    hasGarbageChute: true,
    hasConcierge: true,
    hasGatedArea: false,
    renovation: 'EURO',
    windowView: 'STREET',
    bathroomType: 'SEPARATE',
    furnished: 'PARTIAL',
  },
  {
    title: 'Cozy Studio near Central Park',
    description: 'Charming studio apartment just steps from Central Park. Recently updated with modern amenities while maintaining classic NYC character. Features include exposed brick, hardwood floors, and updated kitchen. Building has laundry facilities and roof deck with stunning park views. Ideal for singles or couples seeking a prime location.',
    propertyType: 'STUDIO',
    listingType: 'RENT',
    price: 2200,
    address: '789 Park Avenue, Studio 5C',
    city: 'New York',
    state: 'NY',
    zipCode: '10021',
    district: 'Upper East Side',
    nearestMetro: '68th Street',
    metroDistance: 4,
    latitude: 40.7694,
    longitude: -73.9654,
    area: 450,
    livingArea: 380,
    kitchenArea: 70,
    rooms: 1,
    bedrooms: 0,
    bathrooms: 1,
    floor: 5,
    totalFloors: 8,
    yearBuilt: 1928,
    ceilingHeight: 10,
    balcony: 0,
    loggia: 0,
    parking: 0,
    parkingType: 'STREET',
    buildingType: 'BRICK',
    buildingClass: 'COMFORT',
    buildingName: 'Park Avenue Classic',
    elevatorPassenger: 1,
    elevatorCargo: 0,
    hasGarbageChute: false,
    hasConcierge: false,
    hasGatedArea: false,
    renovation: 'COSMETIC',
    windowView: 'PARK',
    bathroomType: 'COMBINED',
    furnished: 'NONE',
  },
  {
    title: 'Spacious Family House with Garden',
    description: 'Beautiful single-family home perfect for families. This 4-bedroom house features a large backyard with mature trees, updated kitchen with granite counters, and a finished basement. Master bedroom has en-suite bathroom and walk-in closet. Hardwood floors throughout main level. Attached 2-car garage. Excellent school district.',
    propertyType: 'HOUSE',
    listingType: 'SALE',
    price: 875000,
    address: '456 Oak Street',
    city: 'Brooklyn',
    state: 'NY',
    zipCode: '11215',
    district: 'Park Slope',
    nearestMetro: '7th Avenue',
    metroDistance: 8,
    latitude: 40.6681,
    longitude: -73.9822,
    area: 2400,
    livingArea: 1800,
    kitchenArea: 280,
    rooms: 8,
    bedrooms: 4,
    bathrooms: 2.5,
    floor: 1,
    totalFloors: 2,
    yearBuilt: 1995,
    ceilingHeight: 9,
    balcony: 0,
    loggia: 1,
    parking: 2,
    parkingType: 'GARAGE',
    buildingType: 'BRICK',
    buildingClass: 'COMFORT',
    buildingName: null,
    elevatorPassenger: 0,
    elevatorCargo: 0,
    hasGarbageChute: false,
    hasConcierge: false,
    hasGatedArea: true,
    renovation: 'EURO',
    windowView: 'COURTYARD',
    bathroomType: 'MULTIPLE',
    furnished: 'NONE',
  },
  {
    title: 'Investment Opportunity - Commercial Space',
    description: 'Prime commercial space in high-traffic area. Currently configured as retail with large storefront windows. Can be converted to office or restaurant use. Includes basement storage. Long-term tenant in place with 3 years remaining on lease. Excellent cap rate and stable income stream.',
    propertyType: 'COMMERCIAL',
    listingType: 'SALE',
    price: 1500000,
    address: '1000 Main Street',
    city: 'New York',
    state: 'NY',
    zipCode: '10012',
    district: 'SoHo',
    nearestMetro: 'Spring Street',
    metroDistance: 2,
    latitude: 40.7243,
    longitude: -73.9973,
    area: 3500,
    livingArea: null,
    kitchenArea: null,
    rooms: null,
    bedrooms: null,
    bathrooms: 2,
    floor: 1,
    totalFloors: 5,
    yearBuilt: 1910,
    ceilingHeight: 14,
    balcony: 0,
    loggia: 0,
    parking: 0,
    parkingType: 'STREET',
    buildingType: 'BRICK',
    buildingClass: 'BUSINESS',
    buildingName: 'SoHo Commercial Building',
    elevatorPassenger: 1,
    elevatorCargo: 1,
    hasGarbageChute: false,
    hasConcierge: false,
    hasGatedArea: false,
    renovation: 'NONE',
    windowView: 'STREET',
    bathroomType: 'SEPARATE',
    furnished: 'NONE',
  },
]

async function main() {
  console.log(`Creating properties for user: ${USER_ID}`)

  for (const property of properties) {
    const created = await prisma.property.create({
      data: {
        ...property,
        userId: USER_ID,
        status: 'ACTIVE',
      },
    })
    console.log(`Created: ${created.title} (ID: ${created.id})`)
  }

  console.log(`\nSuccessfully created ${properties.length} properties!`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
